spring:
  cloud:
    config:
      discovery:
        enabled: false
      enabled: false
      retry:
        max-attempts: 1


eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10

  instance:
    appname: ${spring.application.name}
    instanceId: ${spring.application.name}:@project.version@:${random.value}
    #instanceId: ${spring.application.name}:${spring.application.instance-id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10



info:
  app:
    name: Spring Sample Application
    description: This is my first spring boot application
    version: @project.version@
  java-version: ${java.specification.version}
  java-vendor: ${java.specification.vendor}